services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: applo-backend
    network_mode: "host"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: applo-frontend
    network_mode: "host"
    environment:
      - BACKEND_URL=http://localhost:5000
    restart: unless-stopped
