"""add user_id to inventory

Revision ID: 0114b1f94f46
Revises: 8af796c5858b
Create Date: 2026-06-11 16:46:09.738290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0114b1f94f46'
down_revision: Union[str, Sequence[str], None] = '8af796c5858b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'inventory', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'user_id')
    # ### end Alembic commands ###
