"""create user table

Revision ID: 0b9556e101af
Revises: 
Create Date: 2026-06-03 23:58:50.700749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b9556e101af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('userType', sa.Enum('admin', 'buyer', 'seller', name='userenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('age >= 18 and age < 80', name='check_age'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    # Drop tables in correct order (child before parent due to foreign keys)
    op.drop_table('employees')
    op.drop_table('departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # Recreate tables in correct order (parent before child due to foreign keys)
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('departments_pkey')),
    sa.UniqueConstraint('name', name=op.f('departments_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MANAGER', 'EMPLOYEE', name='employeetype'), autoincrement=False, nullable=False),
    sa.Column('departed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('age >= 18', name=op.f('check_age')),
    sa.CheckConstraint('salary >= 0', name=op.f('check_salary')),
    sa.ForeignKeyConstraint(['departed_id'], ['departments.id'], name=op.f('employees_departed_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey'))
    )
    # ### end Alembic commands ###
