"""add profile_picture_url to users

Revision ID: 0d5b75d75238
Revises: 9f377aa8a5bb
Create Date: 2026-06-13 22:26:22.632989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5b75d75238'
down_revision: Union[str, Sequence[str], None] = '9f377aa8a5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###
