"""merge product and inventory

Revision ID: a0a8f58df168
Revises: 0114b1f94f46
Create Date: 2026-06-11 23:55:39.695410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0a8f58df168'
down_revision: Union[str, Sequence[str], None] = '0114b1f94f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first
    op.add_column('products', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))

    # Populate data from inventory into products
    op.execute(
        "UPDATE products p "
        "SET user_id = i.user_id, sku = i.sku, stock = i.quantity "
        "FROM inventory i "
        "WHERE p.id = i.product_id"
    )

    # For any product that did not have an inventory entry, give a default seller (first user) and default stock
    op.execute(
        "UPDATE products "
        "SET user_id = (SELECT id FROM users LIMIT 1) "
        "WHERE user_id IS NULL"
    )
    op.execute(
        "UPDATE products "
        "SET stock = 50 "
        "WHERE stock IS NULL"
    )

    # Now make the required columns NOT NULL
    op.alter_column('products', 'user_id', nullable=False)
    op.alter_column('products', 'stock', nullable=False, server_default='50')

    # Drop inventory table
    op.drop_table('inventory')

    # Add foreign key constraint
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'user_id')
    op.create_table('inventory',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('inventory_product_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('inventory_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_pkey')),
    sa.UniqueConstraint('product_id', name=op.f('inventory_product_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('sku', name=op.f('inventory_sku_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
