"""added refresh tokens table

Revision ID: a8ea55d4efb0
Revises: d7fbc9ad479a
Create Date: 2026-06-04 23:59:43.869852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ea55d4efb0'
down_revision: Union[str, Sequence[str], None] = 'd7fbc9ad479a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
