"""create subcategories table and update category product relationship

Revision ID: e7f6ae9d2afe
Revises: 32c5e8c2a05d
Create Date: 2026-06-11 01:27:06.940974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f6ae9d2afe'
down_revision: Union[str, Sequence[str], None] = '32c5e8c2a05d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'categories', ['name'])
    op.drop_constraint(op.f('categories_parent_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    op.add_column('products', sa.Column('subcategory_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_column('products', 'subcategory_id')
    op.add_column('categories', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_parent_id_fkey'), 'categories', 'categories', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_table('subcategories')
    # ### end Alembic commands ###
